var group__ADC__Exported__Constants =
[
    [ "ADC_Common_mode", "group__ADC__Common__mode.html", "group__ADC__Common__mode" ],
    [ "ADC_Direct_memory_access_mode_for_multi_mode", "group__ADC__Direct__memory__access__mode__for__multi__mode.html", "group__ADC__Direct__memory__access__mode__for__multi__mode" ],
    [ "ADC_Prescaler", "group__ADC__Prescaler.html", "group__ADC__Prescaler" ],
    [ "ADC_analog_watchdog_selection", "group__ADC__analog__watchdog__selection.html", "group__ADC__analog__watchdog__selection" ],
    [ "ADC_channels", "group__ADC__channels.html", "group__ADC__channels" ],
    [ "ADC_data_align", "group__ADC__data__align.html", "group__ADC__data__align" ],
    [ "ADC_delay_between_2_sampling_phases", "group__ADC__delay__between__2__sampling__phases.html", "group__ADC__delay__between__2__sampling__phases" ],
    [ "ADC_external_trigger_edge_for_injected_channels_conversion", "group__ADC__external__trigger__edge__for__injected__channels__conversion.html", "group__ADC__external__trigger__edge__for__injected__channels__conversion" ],
    [ "ADC_external_trigger_edge_for_regular_channels_conversion", "group__ADC__external__trigger__edge__for__regular__channels__conversion.html", "group__ADC__external__trigger__edge__for__regular__channels__conversion" ],
    [ "ADC_extrenal_trigger_sources_for_injected_channels_conversion", "group__ADC__extrenal__trigger__sources__for__injected__channels__conversion.html", "group__ADC__extrenal__trigger__sources__for__injected__channels__conversion" ],
    [ "ADC_extrenal_trigger_sources_for_regular_channels_conversion", "group__ADC__extrenal__trigger__sources__for__regular__channels__conversion.html", "group__ADC__extrenal__trigger__sources__for__regular__channels__conversion" ],
    [ "ADC_flags_definition", "group__ADC__flags__definition.html", "group__ADC__flags__definition" ],
    [ "ADC_injected_channel_selection", "group__ADC__injected__channel__selection.html", "group__ADC__injected__channel__selection" ],
    [ "ADC_injected_length", "group__ADC__injected__length.html", "group__ADC__injected__length" ],
    [ "ADC_injected_offset", "group__ADC__injected__offset.html", "group__ADC__injected__offset" ],
    [ "ADC_injected_rank", "group__ADC__injected__rank.html", "group__ADC__injected__rank" ],
    [ "ADC_interrupts_definition", "group__ADC__interrupts__definition.html", "group__ADC__interrupts__definition" ],
    [ "ADC_regular_discontinuous_mode_number", "group__ADC__regular__discontinuous__mode__number.html", "group__ADC__regular__discontinuous__mode__number" ],
    [ "ADC_regular_length", "group__ADC__regular__length.html", "group__ADC__regular__length" ],
    [ "ADC_regular_rank", "group__ADC__regular__rank.html", "group__ADC__regular__rank" ],
    [ "ADC_resolution", "group__ADC__resolution.html", "group__ADC__resolution" ],
    [ "ADC_sampling_times", "group__ADC__sampling__times.html", "group__ADC__sampling__times" ],
    [ "ADC_thresholds", "group__ADC__thresholds.html", "group__ADC__thresholds" ],
    [ "IS_ADC_ALL_PERIPH", "group__ADC__Exported__Constants.html#gaf5d6bd0153464912e0eaccb1af1aefb2", null ]
];