var modules =
[
    [ "CMSIS", "group__CMSIS.html", "group__CMSIS" ],
    [ "CMSIS Core Definitions", "group__CMSIS__core__definitions.html", "group__CMSIS__core__definitions" ],
    [ "CMSIS Core Function Interface", "group__CMSIS__Core__FunctionInterface.html", "group__CMSIS__Core__FunctionInterface" ],
    [ "CMSIS Core Instruction Interface", "group__CMSIS__Core__InstructionInterface.html", null ],
    [ "CMSIS Core Register", "group__CMSIS__core__register.html", "group__CMSIS__core__register" ],
    [ "CMSIS MISRA-C:2004 Compliance Exceptions", "group__CMSIS__MISRA__Exceptions.html", null ],
    [ "CMSIS SIMD Intrinsics", "group__CMSIS__SIMD__intrinsics.html", null ],
    [ "STM32F4xx_StdPeriph_Driver", "group__STM32F4xx__StdPeriph__Driver.html", "group__STM32F4xx__StdPeriph__Driver" ],
    [ "crDELAY", "group__crDELAY.html", null ],
    [ "crQUEUE_RECEIVE", "group__crQUEUE__RECEIVE.html", null ],
    [ "crQUEUE_RECEIVE_FROM_ISR", "group__crQUEUE__RECEIVE__FROM__ISR.html", null ],
    [ "crQUEUE_SEND", "group__crQUEUE__SEND.html", null ],
    [ "crQUEUE_SEND_FROM_ISR", "group__crQUEUE__SEND__FROM__ISR.html", null ],
    [ "crSTART", "group__crSTART.html", null ],
    [ "uxTaskPriorityGet", "group__uxTaskPriorityGet.html", null ],
    [ "vCoRoutineSchedule", "group__vCoRoutineSchedule.html", null ],
    [ "vSemaphoreCreateBinary", "group__vSemaphoreCreateBinary.html", null ],
    [ "vSemaphoreCreateMutex", "group__vSemaphoreCreateMutex.html", null ],
    [ "vTaskDelay", "group__vTaskDelay.html", null ],
    [ "vTaskDelayUntil", "group__vTaskDelayUntil.html", null ],
    [ "vTaskDelete", "group__vTaskDelete.html", null ],
    [ "vTaskEndScheduler", "group__vTaskEndScheduler.html", null ],
    [ "vTaskPrioritySet", "group__vTaskPrioritySet.html", null ],
    [ "vTaskResume", "group__vTaskResume.html", null ],
    [ "vTaskResumeFromISR", "group__vTaskResumeFromISR.html", null ],
    [ "vTaskStartScheduler", "group__vTaskStartScheduler.html", null ],
    [ "vTaskSuspend", "group__vTaskSuspend.html", null ],
    [ "vTaskSuspendAll", "group__vTaskSuspendAll.html", null ],
    [ "xCoRoutineCreate", "group__xCoRoutineCreate.html", null ],
    [ "xQueueCreate", "group__xQueueCreate.html", null ],
    [ "xQueueReceive", "group__xQueueReceive.html", null ],
    [ "xQueueReceiveFromISR", "group__xQueueReceiveFromISR.html", null ],
    [ "xQueueSend", "group__xQueueSend.html", null ],
    [ "xQueueSendFromISR", "group__xQueueSendFromISR.html", null ],
    [ "xSemaphoreCreateCounting", "group__xSemaphoreCreateCounting.html", null ],
    [ "xSemaphoreGive", "group__xSemaphoreGive.html", null ],
    [ "xSemaphoreGiveFromISR", "group__xSemaphoreGiveFromISR.html", null ],
    [ "xSemaphoreGiveRecursive", "group__xSemaphoreGiveRecursive.html", null ],
    [ "xSemaphoreTake", "group__xSemaphoreTake.html", null ],
    [ "xSemaphoreTakeRecursive", "group__xSemaphoreTakeRecursive.html", null ],
    [ "xTaskCreate", "group__xTaskCreate.html", null ],
    [ "xTaskCreateRestricted", "group__xTaskCreateRestricted.html", null ],
    [ "xTaskResumeAll", "group__xTaskResumeAll.html", null ]
];